version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: gorgeous
      POSTGRES_DB: online_store_db
    ports:
      - "5432:5432"
    volumes:
    - C:/Users/George/Desktop/Projects/JavaMiddle/homework/spring-data/core/src/main/resources/dump.sql:/infile
    - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: